#pragma once

enum SecureMode
{
	MODE_SECURE,
	MODE_NON_SECURE,
};

enum OperMode
{
	MODE_LEARNING,
	MODE_RUN,
	MODE_TEST_RUN,
};

enum MsgReq
{
	MSG_LOGIN_REGISTER_USER = 1000,
	MSG_LOGIN_REQUEST = 1001,
	MSG_LOGIN_SUPER_USER = 1,
	MSG_LOGIN_USER = 2,
	MSG_CONTROL_MODE_RUN = 1100,
	MSG_CONTROL_MODE_LEARNING = 1101,
	MSG_CONTROL_MODE_TEST = 1102,
	MSG_CONTROL_START_SEND_IMAGE = 1200,
	MSG_CONTROL_STOP_SEND_IMAGE = 1201,
};

enum MsgRecv
{
	MSG_OK = 1200,
	MSG_LEARNING_COMPLETE = 1201,
	MSG_RUN_MODE = 1202,
	MSG_LEARNING_MODE = 1203,
	MSG_TEST_MODE = 1204,
	MSG_SERVER_ERROR = 1500,
	MSG_LOGIN_DUPLICATED_ID = 1501,
	MSG_LOGIN_ERROR = 1502,
	MSG_NO_PERMISSION = 1503,
};
