// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protocol_2eproto;
namespace protocol_msg {
class ProtocolMsg;
struct ProtocolMsgDefaultTypeInternal;
extern ProtocolMsgDefaultTypeInternal _ProtocolMsg_default_instance_;
}  // namespace protocol_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::protocol_msg::ProtocolMsg* Arena::CreateMaybeMessage<::protocol_msg::ProtocolMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protocol_msg {

// ===================================================================

class ProtocolMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol_msg.ProtocolMsg) */ {
 public:
  inline ProtocolMsg() : ProtocolMsg(nullptr) {}
  ~ProtocolMsg() override;
  explicit constexpr ProtocolMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProtocolMsg(const ProtocolMsg& from);
  ProtocolMsg(ProtocolMsg&& from) noexcept
    : ProtocolMsg() {
    *this = ::std::move(from);
  }

  inline ProtocolMsg& operator=(const ProtocolMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtocolMsg& operator=(ProtocolMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtocolMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtocolMsg* internal_default_instance() {
    return reinterpret_cast<const ProtocolMsg*>(
               &_ProtocolMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ProtocolMsg& a, ProtocolMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(ProtocolMsg* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtocolMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ProtocolMsg* New() const final {
    return new ProtocolMsg();
  }

  ProtocolMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ProtocolMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ProtocolMsg& from);
  void MergeFrom(const ProtocolMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtocolMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol_msg.ProtocolMsg";
  }
  protected:
  explicit ProtocolMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserIdFieldNumber = 2,
    kPasswordFieldNumber = 3,
    kImgDataFieldNumber = 8,
    kMsgTypeFieldNumber = 1,
    kAuthorityFieldNumber = 4,
    kOperationModeFieldNumber = 5,
    kNumImageFieldNumber = 6,
    kImgSizeFieldNumber = 7,
  };
  // string user_id = 2;
  void clear_user_id();
  const std::string& user_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_id();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // string password = 3;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // bytes img_data = 8;
  void clear_img_data();
  const std::string& img_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_img_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_img_data();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_img_data();
  void set_allocated_img_data(std::string* img_data);
  private:
  const std::string& _internal_img_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_img_data(const std::string& value);
  std::string* _internal_mutable_img_data();
  public:

  // int32 msg_type = 1;
  void clear_msg_type();
  ::PROTOBUF_NAMESPACE_ID::int32 msg_type() const;
  void set_msg_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_msg_type() const;
  void _internal_set_msg_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 authority = 4;
  void clear_authority();
  ::PROTOBUF_NAMESPACE_ID::int32 authority() const;
  void set_authority(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_authority() const;
  void _internal_set_authority(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 operation_mode = 5;
  void clear_operation_mode();
  ::PROTOBUF_NAMESPACE_ID::int32 operation_mode() const;
  void set_operation_mode(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_operation_mode() const;
  void _internal_set_operation_mode(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 num_image = 6;
  void clear_num_image();
  ::PROTOBUF_NAMESPACE_ID::int32 num_image() const;
  void set_num_image(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_num_image() const;
  void _internal_set_num_image(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 img_size = 7;
  void clear_img_size();
  ::PROTOBUF_NAMESPACE_ID::int32 img_size() const;
  void set_img_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_img_size() const;
  void _internal_set_img_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:protocol_msg.ProtocolMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr img_data_;
  ::PROTOBUF_NAMESPACE_ID::int32 msg_type_;
  ::PROTOBUF_NAMESPACE_ID::int32 authority_;
  ::PROTOBUF_NAMESPACE_ID::int32 operation_mode_;
  ::PROTOBUF_NAMESPACE_ID::int32 num_image_;
  ::PROTOBUF_NAMESPACE_ID::int32 img_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProtocolMsg

// int32 msg_type = 1;
inline void ProtocolMsg::clear_msg_type() {
  msg_type_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ProtocolMsg::_internal_msg_type() const {
  return msg_type_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ProtocolMsg::msg_type() const {
  // @@protoc_insertion_point(field_get:protocol_msg.ProtocolMsg.msg_type)
  return _internal_msg_type();
}
inline void ProtocolMsg::_internal_set_msg_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  msg_type_ = value;
}
inline void ProtocolMsg::set_msg_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_msg_type(value);
  // @@protoc_insertion_point(field_set:protocol_msg.ProtocolMsg.msg_type)
}

// string user_id = 2;
inline void ProtocolMsg::clear_user_id() {
  user_id_.ClearToEmpty();
}
inline const std::string& ProtocolMsg::user_id() const {
  // @@protoc_insertion_point(field_get:protocol_msg.ProtocolMsg.user_id)
  return _internal_user_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProtocolMsg::set_user_id(ArgT0&& arg0, ArgT... args) {
 
 user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protocol_msg.ProtocolMsg.user_id)
}
inline std::string* ProtocolMsg::mutable_user_id() {
  // @@protoc_insertion_point(field_mutable:protocol_msg.ProtocolMsg.user_id)
  return _internal_mutable_user_id();
}
inline const std::string& ProtocolMsg::_internal_user_id() const {
  return user_id_.Get();
}
inline void ProtocolMsg::_internal_set_user_id(const std::string& value) {
  
  user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ProtocolMsg::_internal_mutable_user_id() {
  
  return user_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ProtocolMsg::release_user_id() {
  // @@protoc_insertion_point(field_release:protocol_msg.ProtocolMsg.user_id)
  return user_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ProtocolMsg::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {
    
  } else {
    
  }
  user_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_id,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:protocol_msg.ProtocolMsg.user_id)
}

// string password = 3;
inline void ProtocolMsg::clear_password() {
  password_.ClearToEmpty();
}
inline const std::string& ProtocolMsg::password() const {
  // @@protoc_insertion_point(field_get:protocol_msg.ProtocolMsg.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProtocolMsg::set_password(ArgT0&& arg0, ArgT... args) {
 
 password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protocol_msg.ProtocolMsg.password)
}
inline std::string* ProtocolMsg::mutable_password() {
  // @@protoc_insertion_point(field_mutable:protocol_msg.ProtocolMsg.password)
  return _internal_mutable_password();
}
inline const std::string& ProtocolMsg::_internal_password() const {
  return password_.Get();
}
inline void ProtocolMsg::_internal_set_password(const std::string& value) {
  
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ProtocolMsg::_internal_mutable_password() {
  
  return password_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ProtocolMsg::release_password() {
  // @@protoc_insertion_point(field_release:protocol_msg.ProtocolMsg.password)
  return password_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ProtocolMsg::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:protocol_msg.ProtocolMsg.password)
}

// int32 authority = 4;
inline void ProtocolMsg::clear_authority() {
  authority_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ProtocolMsg::_internal_authority() const {
  return authority_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ProtocolMsg::authority() const {
  // @@protoc_insertion_point(field_get:protocol_msg.ProtocolMsg.authority)
  return _internal_authority();
}
inline void ProtocolMsg::_internal_set_authority(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  authority_ = value;
}
inline void ProtocolMsg::set_authority(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_authority(value);
  // @@protoc_insertion_point(field_set:protocol_msg.ProtocolMsg.authority)
}

// int32 operation_mode = 5;
inline void ProtocolMsg::clear_operation_mode() {
  operation_mode_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ProtocolMsg::_internal_operation_mode() const {
  return operation_mode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ProtocolMsg::operation_mode() const {
  // @@protoc_insertion_point(field_get:protocol_msg.ProtocolMsg.operation_mode)
  return _internal_operation_mode();
}
inline void ProtocolMsg::_internal_set_operation_mode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  operation_mode_ = value;
}
inline void ProtocolMsg::set_operation_mode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_operation_mode(value);
  // @@protoc_insertion_point(field_set:protocol_msg.ProtocolMsg.operation_mode)
}

// int32 num_image = 6;
inline void ProtocolMsg::clear_num_image() {
  num_image_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ProtocolMsg::_internal_num_image() const {
  return num_image_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ProtocolMsg::num_image() const {
  // @@protoc_insertion_point(field_get:protocol_msg.ProtocolMsg.num_image)
  return _internal_num_image();
}
inline void ProtocolMsg::_internal_set_num_image(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  num_image_ = value;
}
inline void ProtocolMsg::set_num_image(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_num_image(value);
  // @@protoc_insertion_point(field_set:protocol_msg.ProtocolMsg.num_image)
}

// int32 img_size = 7;
inline void ProtocolMsg::clear_img_size() {
  img_size_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ProtocolMsg::_internal_img_size() const {
  return img_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ProtocolMsg::img_size() const {
  // @@protoc_insertion_point(field_get:protocol_msg.ProtocolMsg.img_size)
  return _internal_img_size();
}
inline void ProtocolMsg::_internal_set_img_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  img_size_ = value;
}
inline void ProtocolMsg::set_img_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_img_size(value);
  // @@protoc_insertion_point(field_set:protocol_msg.ProtocolMsg.img_size)
}

// bytes img_data = 8;
inline void ProtocolMsg::clear_img_data() {
  img_data_.ClearToEmpty();
}
inline const std::string& ProtocolMsg::img_data() const {
  // @@protoc_insertion_point(field_get:protocol_msg.ProtocolMsg.img_data)
  return _internal_img_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProtocolMsg::set_img_data(ArgT0&& arg0, ArgT... args) {
 
 img_data_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protocol_msg.ProtocolMsg.img_data)
}
inline std::string* ProtocolMsg::mutable_img_data() {
  // @@protoc_insertion_point(field_mutable:protocol_msg.ProtocolMsg.img_data)
  return _internal_mutable_img_data();
}
inline const std::string& ProtocolMsg::_internal_img_data() const {
  return img_data_.Get();
}
inline void ProtocolMsg::_internal_set_img_data(const std::string& value) {
  
  img_data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ProtocolMsg::_internal_mutable_img_data() {
  
  return img_data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ProtocolMsg::release_img_data() {
  // @@protoc_insertion_point(field_release:protocol_msg.ProtocolMsg.img_data)
  return img_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ProtocolMsg::set_allocated_img_data(std::string* img_data) {
  if (img_data != nullptr) {
    
  } else {
    
  }
  img_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), img_data,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:protocol_msg.ProtocolMsg.img_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol_msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2eproto
